MvcLoadDownTest/Models/ErrorViewModel.cs
using System;

namespace MvcLoadDownTest.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcLoadDownTest/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
//ITEXTSHARP REALIZA O MERGE DO DOCUMENTO
using iTextSharp.text.pdf;
using iTextSharp.text;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MvcLoadDownTest.Controllers
{
    public class GalleryController : Controller
    {
        //REFERENCIA LOCAL AMBIENTE/PASTA
        IWebHostEnvironment _appEnvironment;
        public GalleryController(IWebHostEnvironment env)
        {
            _appEnvironment = env;
        }

        //private readonly string wwwrootDirectory =
        //    Path.Combine(Directory.GetCurrentDirectory(), "wwwroot");

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }


        // RECEBE O FILE
        //COPIA PARA WWWROOT
        //CRIA O MERGE E COPIA PARA WWWROOT
        [HttpPost]
        public async Task<IActionResult> UploadToApp(List<IFormFile> file)

        {

            List<string> uploadedFiles = new List<string>();
            List<PdfReader> pdfReaderList = new List<PdfReader>();

            var localeUpload = _appEnvironment.WebRootPath + "\\Original\\";
            var localeUploadMerge = _appEnvironment.WebRootPath + "\\Merge\\";

            if (!Directory.Exists(localeUpload))
            {
                Directory.CreateDirectory(localeUpload);
            }  
            
            if (!Directory.Exists(localeUploadMerge))
            {
                Directory.CreateDirectory(localeUploadMerge);
            }



            foreach (var files in file)
            {

                if (files == null || files.Length == 0)
                { ViewData["ERRO"] = "ERRO: Selecione algum arquivo"; return View(ViewData); }
            }


            foreach (var files in file)
            {
                
                var nameUpload = DateTime.Now.Ticks.ToString() + Path.GetExtension(files.FileName);
                var path = Path.Combine(
                    localeUpload, nameUpload);
            }
                foreach (IFormFile postedFile in file)
            {
            string fileName = Path.GetFileName(postedFile.FileName);
            using (FileStream stream = new FileStream(Path.Combine(localeUpload, fileName), FileMode.Create))
            {
                postedFile.CopyTo(stream);
                uploadedFiles.Add(Path.Combine(localeUpload, fileName));
            }

            }

            foreach (string pdfFile in uploadedFiles)
            {

                PdfReader pdfReader = new PdfReader(Path.Combine(localeUpload, pdfFile));

                pdfReaderList.Add(pdfReader);
            }

            Document document = new Document(PageSize.A4, 0, 0, 0, 0);


            PdfWriter writer = PdfWriter.GetInstance(document, new FileStream(Path.Combine(localeUploadMerge, RandomString(8).ToString()+".pdf"), FileMode.Create));
            document.Open();
            foreach (PdfReader reader in pdfReaderList)
            {
                for (int i = 1; i <= reader.NumberOfPages; i++)
                {
                    PdfImportedPage page = writer.GetImportedPage(reader, i);
                    document.Add(Image.GetInstance(page));
                }
            }
            document.Close();


            RedirectToAction("Index");
            { ViewData["OK"] = "OK: Merge realizado"; return View(ViewData); }

        }

        private static Random random = new Random();


        //GERADOR NOME RANDOM
        public string RandomString(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
                .Select(s => s[random.Next(s.Length)]).ToArray());
        }

    }
}

MvcLoadDownTest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcLoadDownTest.Models;

namespace MvcLoadDownTest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcLoadDownTest/Views/Gallery/Index.cshtml
@*
	For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
	ViewData["Title"] = "Home Page";
}

@*<div class="container">
	@using (Html.BeginForm("Index","Gallery", FormMethod.Post, new { enctype = "multipart/form-data" }))
	{
	<div class="row">
	<div class="form-group col-md6">
	<input type="file" class="form-control"  id="file" />
	</div>
	</div>

	<div class="row">
	<div class="form-group col-md6">
	<input type="submit" name="filesubmit" id="file"/>
	</div>
	</div>
	}



	</div>*@


<h1>Upload</h1>
<hr />
<div class="card">
	<div class="card-header">
		Upload File
	</div>
	<div class="card-body">
		<iv class="container">
			<section>
				<form class="was-validated" method="post" enctype="multipart/form-data" asp-controller="Gallery" asp-action="UploadToApp">
					<div class="row">
						<div class="col-md-10 form-group">
							<div class=" col-md-10 custom-file">
								<input type="file" class="custom-file-input" name="file" multiple required>
								<label class="custom-file-label" for="validatedCustomFile">Choose file...</label>
								<div class="invalid-feedback">Input PDF</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-10 form-group">
							<div class=" col-md-10 custom-file">
								<input type="file" class="custom-file-input" name="file" multiple required>
								<label class="custom-file-label" for="validatedCustomFile">Choose file...</label>
								<div class="invalid-feedback">Input PDF</div>
							</div>
						</div>
					</div>
					<div class="row">
					</div>
					<hr />
					<div class="row">
						<div class="form-group">
							<div class="col-md-10">
								<input class="btn btn-primary" type="submit" value="Upload" />
							</div>
						</div>
					</div>
				</form>
			</section>
	</div>
</div>

MvcLoadDownTest/Views/Gallery/UploadToApp.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Index";
}


<h1>Upload</h1>
<hr />

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        @if (ViewData["ERRO"] != null)
        {
            <h2 class="display-4">@ViewData["ERRO"]</h2>
        }
    </div>
    <div class="container">
        @if (ViewData["OK"] != null)
        {
            <h2 class="display-4">@ViewData["OK"]</h2>
        }
    </div>
</div>

MvcLoadDownTest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Upload PDF</h1>
    <p>Upload e Merge PDF Test.</p>
</div>

MvcLoadDownTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcLoadDownTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcLoadDownTest</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gallery" asp-action="Index">Gallery</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcLoadDownTest
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>